### ISSUE TITLE
onChange handler can fire SIGHUP too early

### ISSUE THREAD

**Issue by tgross** [tgross/workshop-autopilot#12]
From https://github.com/joyent/containerpilot/issues/173

@papertigers wrote:

> It would be nice if CP had a mechanism for knowing when the application it's wrapping is in a suitable state. Taking the sales app in https://github.com/autopilotpattern/workshop as an example, we hit a race condition between CP and node. In some cases CP fires the SIGHUP before node has a chance to finish launching and before node registers its event handler. Thus killing the container instead of having its intended purpose.

@tgross wrote:

> ContainerPilot doesn't fire SIGHUP, the user-defined `onChange` behavior does (in that example). The `onChange` behavior is entirely in the hands of the application developer and so they have the responsibility to make sure that their application and `onChange` behavior will play nice together.

So the solution in this case is that instead of [calling `pkill` directly from ContainerPilot](https://github.com/autopilotpattern/workshop/blob/0e9b46382cde8fa6e53426c0dd0f45097324d1bf/sales/containerpilot.json#L16) we should have a script hook that checks to make sure Node is up and running first before firing the `pkill`.

**Comment by tgross** [comment]
ref https://devhub.joyent.com/jira/browse/OS-5446 for internal Joyent folks

**Comment by tgross** [comment]
This will be fixed once 8df3b2bdb514cb1ae8c692146debfbbb5a81a30d is merged in https://github.com/autopilotpattern/workshop/pull/9

**Comment by misterbisson** [comment]
https://github.com/autopilotpattern/workshop/pull/9 is merged
