### ISSUE TITLE
Linkerd

### ISSUE THREAD

**Issue by Smithx10** [tgross/workshop-autopilot#22]
Everyone,

Would adding LinkerD on top of this stack gain us some benefits?  

Thank You,
Bruce Smith

**Comment by tgross** [comment]
@Smithx10 what would adding that component add to this stack?

**Comment by Smithx10** [comment]
Tim Gross,
I watched the https://www.youtube.com/watch?v=eC4s-XwUbOk  and https://www.youtube.com/watch?list=PLI9FkLPXDscDB0gevkhEnyfgIfWF5yk4V&v=VGAFFkn5PiE About linkerd on Mesosphere and mesos (which am running on).  It is a layer5 router which proxies RPC.  It allows you to do weighted migrations etc.  

https://github.com/BuoyantIO/linkerd-examples  shows some examples that are from the second video. 

I don't know if it fits well or not,  it would be replacing nginx in this example,  maybe It would be worth making a demo with it.

**Comment by tgross** [comment]
> It is a layer5 router which proxies RPC. It allows you to do weighted migrations etc.

I'm familiar with linkerd, but I'm asking why you think it might have value. It's really the opposite approach from the Autopilot Pattern. In Autopilot Pattern applications, the application is always able to make connections directly to their service dependencies. Using linkerd is very similar to using bamboo or HAProxy agent on the compute node, and this adds a hop between services and adds an additional layer of orchestration.

**Comment by Smithx10** [comment]
Gotcha,  I think it can run side car.  I didn't think it would work in the same manner as running it like they do on mesosphere.  It's too frameworkie :)  Understood.

**Comment by tgross** [comment]
No updates on this so I'm closing.
