### ISSUE TITLE
consulite and piloted in release?

### ISSUE THREAD

**Issue by sholtomaud** [tgross/workshop-autopilot#25]
Hi I noticed that you had some articles on consulite and piloted https://www.joyent.com/blog/using-nodejs-in-docker, but these aren't used in the release version.

Is the release version going to be updated?

**Comment by geek** [comment]
@shotlom thanks for pointing that out. I added a [release](https://github.com/autopilotpattern/workshop/releases/tag/v3.0) that aligns with the article.
