### ISSUE TITLE
No cluster leader error

### ISSUE THREAD

**Issue by ht512512** [tgross/workshop-autopilot#28]
I started out with the workshop example but I am not able to get it to work due to errors (no cluster leader). I have included the log below. Perhaps something is missing!

OS: Ubuntu Server 16.04 LTS
Docker version 17.03.1-ce, build c6d412e
Workshop code: Latest 3.0 No modifications
Log:
  ~/dev/workshop$ sudo docker-compose up

  Starting workshop_consul_1 ...
  Starting workshop_consul_1 ... done
  Starting workshop_sales_1 ...
  Starting workshop_customers_1 ...
  Starting workshop_sales_1
  Starting workshop_nginx_1 ...
  Starting workshop_customers_1
  Starting workshop_nginx_1 ... done
  Attaching to workshop_consul_1, workshop_customers_1, workshop_sales_1, workshop_nginx_1
  consul_1     | ==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
  consul_1     | ==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
  consul_1     | ==> Starting raft data migration...
  consul_1     | ==> Starting Consul agent...
  consul_1     | ==> Starting Consul agent RPC...
  consul_1     | ==> Consul agent running!
  consul_1     |          Node name: '191c5baf659b'
  consul_1     |         Datacenter: 'dc1'
  consul_1     |             Server: true (bootstrap: true)
  consul_1     |        Client Addr: 0.0.0.0 (HTTP: 8500, HTTPS: -1, DNS: 53, RPC: 8400)
  consul_1     |       Cluster Addr: 172.17.0.2 (LAN: 8301, WAN: 8302)
  consul_1     |     Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
  consul_1     |              Atlas: <disabled>
  consul_1     |
  consul_1     | ==> Log data will now stream in as it occurs:
  consul_1     |
  consul_1     |     2017/06/05 16:13:04 [INFO] serf: EventMemberJoin: 191c5baf659b 172.17.0.2
  consul_1     |     2017/06/05 16:13:04 [INFO] serf: EventMemberJoin: 191c5baf659b.dc1 172.17.0.2
  consul_1     |     2017/06/05 16:13:04 [INFO] raft: Node at 172.17.0.2:8300 [Follower] entering Follower state
  consul_1     |     2017/06/05 16:13:04 [WARN] serf: Failed to re-join any previously known node
  consul_1     |     2017/06/05 16:13:04 [WARN] serf: Failed to re-join any previously known node
  consul_1     |     2017/06/05 16:13:04 [INFO] consul: adding server 191c5baf659b (Addr: 172.17.0.2:8300) (DC: dc1)
  consul_1     |     2017/06/05 16:13:04 [INFO] consul: adding server 191c5baf659b.dc1 (Addr: 172.17.0.2:8300) (DC: dc1)
  consul_1     |     2017/06/05 16:13:04 [ERR] agent: failed to sync remote state: No cluster leader
  consul_1     |     2017/06/05 16:13:04 [ERR] http: Request /v1/health/service/sales?passing=1&wait=60000ms, error: No cluster leader
  consul_1     |     2017/06/05 16:13:04 [ERR] http: Request /v1/health/service/customers?passing=1&wait=60000ms, error: No cluster leader
  nginx_1      | time="2017-06-05T16:13:04Z" level=debug msg="preStart.RunAndWait start"
  nginx_1      | time="2017-06-05T16:13:04Z" level=debug msg=preStart.Cmd.Run
  nginx_1      | time="2017-06-05T16:13:04Z" level=info msg="2017/06/05 16:13:04 [ERR] (view) \"service(customers)\" health services: error fetching: Unexpected response code: 500 (No cluster leader)" process=PreStart
  nginx_1      | time="2017-06-05T16:13:04Z" level=info msg="2017/06/05 16:13:04 [ERR] (runner) watcher reported error: health services: error fetching: Unexpected response code: 500 (No cluster leader)" process=PreStart
  nginx_1      | time="2017-06-05T16:13:04Z" level=info msg="Consul Template returned errors:" process=PreStart
  nginx_1      | time="2017-06-05T16:13:04Z" level=debug msg="preStart.RunAndWait end"
  nginx_1      | time="2017-06-05T16:13:04Z" level=debug msg="nginx.RunAndWait start"
  nginx_1      | time="2017-06-05T16:13:04Z" level=debug msg=nginx.Cmd.Run
  consul_1     |     2017/06/05 16:13:04 [ERR] http: Request /v1/health/service/sales?passing&near=agent, error: No cluster leader
  customers_1  | SyntaxError: Unexpected token N in JSON at position 0
  customers_1  |     at Object.parse (native)
  customers_1  |     at Object.internals.tryParseBuffer (/opt/customers/node_modules/wreck/lib/index.js:536:27)
  customers_1  |     at finish (/opt/customers/node_modules/wreck/lib/index.js:355:32)
  customers_1  |     at wrapped (/opt/customers/node_modules/hoek/lib/index.js:871:20)
  customers_1  |     at onReaderFinish (/opt/customers/node_modules/wreck/lib/index.js:415:16)
  customers_1  |     at g (events.js:291:16)
  customers_1  |     at emitNone (events.js:91:20)
  customers_1  |     at emit (events.js:185:7)
  customers_1  |     at finishMaybe (_stream_writable.js:488:14)
  customers_1  |     at afterWrite (_stream_writable.js:362:3)
  customers_1  | Running Customers app on port 4000
  sales_1      | No database credentials set. Assuming no MySQL backend.
  sales_1      | Running Sales app on port 3000
  consul_1     |     2017/06/05 16:13:05 [WARN] raft: Heartbeat timeout reached, starting election
  consul_1     |     2017/06/05 16:13:05 [INFO] raft: Node at 172.17.0.2:8300 [Candidate] entering Candidate state
  consul_1     |     2017/06/05 16:13:05 [INFO] raft: Election won. Tally: 1
  consul_1     |     2017/06/05 16:13:05 [INFO] raft: Node at 172.17.0.2:8300 [Leader] entering Leader state
  consul_1     |     2017/06/05 16:13:05 [INFO] consul: cluster leadership acquired
  consul_1     |     2017/06/05 16:13:05 [INFO] consul: New leader elected: 191c5baf659b
  consul_1     |     2017/06/05 16:13:05 [INFO] raft: Disabling EnableSingleNode (bootstrap)
  consul_1     |     2017/06/05 16:13:07 [ERR] http: Request /v1/agent/check/pass/customers-22ff43f4fc67?note=ok, error: CheckID does not have associated TTL
  customers_1  | 2017/06/05 16:13:07 Unexpected response code: 500 (CheckID does not have associated TTL)
  customers_1  | Service not registered, registering...
  consul_1     |     2017/06/05 16:13:07 [INFO] agent: Synced service 'customers-22ff43f4fc67'
  consul_1     |     2017/06/05 16:13:07 [INFO] agent: Synced check 'customers-22ff43f4fc67'
  sales_1      | 2017/06/05 16:13:07 Unexpected response code: 500 (CheckID does not have associated TTL)
  sales_1      | Service not registered, registering...
  consul_1     |     2017/06/05 16:13:07 [ERR] http: Request /v1/agent/check/pass/sales-73340260b9ee?note=ok, error: CheckID does not have associated TTL
  consul_1     |     2017/06/05 16:13:07 [INFO] agent: Synced service 'sales-73340260b9ee'
  consul_1     |     2017/06/05 16:13:07 [INFO] agent: Synced check 'sales-73340260b9ee'

**Comment by tgross** [comment]
> I started out with the workshop example but I am not able to get it to work due to errors (no cluster leader).

When you say it doesn't work, what do you mean? These logs show that services are registering with Consul just fine, but that you're getting cluster leadership errors in the logs while Consul is still coming up. Is there some other error condition you're getting?

**Comment by ht512512** [comment]
Tim,
Thanks for the quick response. (1) I thought the errors were serious. (2) I was not able to browse to port 80 (my wrong impression). 

Looks like it is fine; I am able to connect to nginx on port 32782. Closing this. Again, thanks for your help.
